### PR TITLE
Implement Puppet Development Kit for remote_file

### PR DESCRIPTION
**Pull request by reidmv**
https://puppet.com/docs/pdk/1.x/pdk_converting_modules.html

The PDK provides a standard framework for style, building and running tests, and maintaining metadata. While there are no tests currently written for this module, converting to the PDK lowers the barrier to entry for writing them should anyone want to do that in the future.

As part of converting to the PDK many Ruby style edits were made in order to align with the conventional rubocop linting and style tests.

Because Ruby 1.9.x conventions are used, the supported version of Puppet is changed from >=3.x to >=4.6.x. Older versions may work but it is difficult to find documentation for versions of Puppet older than 4.6. The oldest version of Ruby supported by Puppet 4.6 is 1.9.3.

Therefore, this PR also bumps the remote_file version to 2.0.0.

One preexisting bug was identified and fixed as a result of performing basic validation of the changes.

### CODE REVIEW

**Comment by lwf** [comment]
Hey @reidmv, thanks for the PR.

I've pretty much stopped maintaining this module and haven't been a user of Puppet since 2015. Would you be interested in taking over as maintainer, given that most of the code is your work at this point anyway?

**Comment by reidmv** [comment]
@lwf Sure!

Thank you so much for all your original work creating and maintaining this module! IMO this is still one of the best, most flexible unix-philosophy "do one thing and do it well" Puppet types available for fetching and ensuring files from remote sources. Almost 1 million downloads on the Forge suggests other people think it's pretty decent too.

The best way to transition the module to new maintainership would be to migrate it to [Vox Pupuli](https://voxpupuli.org/), a community-run and community-maintained collection of Puppet modules. I'm a Vox Pupuli contributor and would be more than happy to continue to maintain this module module as long as it's needed from there.

There's a [process for migrating](https://voxpupuli.org/docs/#migrating-a-module-to-voxpupuli) it which I can help with. I'll start asking some questions about how to do that, as the docs look like they haven't been updated in awhile.

If migrating the module to Vox Pupuli sounds like the right thing to do, I should be able to do most of the work. You would need to add me as a contributor to this repo, and after that I could do the work of updating the README to indicate the migration, link to Vox Pupuli, and so forth. Let me know if that's how you would like to proceed and I will work on it as I have time. It might take a little while but I can start turning the crank slowly.

Thanks again. This is a great module that provides an elegant solution to managing remote files.

**Comment by lwf** [comment]
I've added you as a contributor to the repository. I'm a bit short on time for maintaining open source projects unrelated to work these days, but I should be able to assist with other things you might need in time.

**Comment by TraGicCode** [comment]
@reidmv Have you made any progress on this migration?

**Comment by reidmv** [comment]
@TraGicCode I think I dead-ended with a conflict between how Vox Pupuli's modulesync config is set up and how the PDK is set up. At the time I was looking the PDK was very new and there wasn't a clear way to integrate it with modulesync.

It's ready to look at again for migration to Vox Pupuli, I think. Worst case scenario, setting up a modulesync config that basically says "don't touch anything in this module" would probably be a path forward.

For now I've merged the PR here and tagged the module 2.0.0 in Git.

**Pull request merged**
