### PR TITLE
Adding suport to set custom HTTP headers

### PR DESCRIPTION
**Pull request by stoiev**
Hi! Sometimes, server could need some unconventional HTTP header for authentication. This pull request provides a way to send custom HTTP on requests.

### CODE REVIEW

**Comment by reidmv** [comment]
I like this.

Before merging, I think the parameter name should be simplified to just `headers`. The term `initial_headers` is technically correct, but unnecessarily specific. Day-to-day users don't need to be thinking about what "initial" means, so we should omit it from the parameter name to reduce cognitive burden.

:+1:

**Comment by lwf** [comment]
Sorry for the late reply. Agreed with @reidmv on initial_headers vs headers. Could you update this pull request to reflect that change? I'll merge it once that's done.

**Comment by stoiev** [comment]
Hi @lwf , @reidmv . Here it goes.

**Comment by lwf** [comment]
Sorry to be picky, but could you amend your first commit? I don't like having "partial" commits in the tree.

**Comment by stoiev** [comment]
No problem, I've rebased those two commits into one and forced a push, that's ok? (I haven't tried it before)

**Comment by lwf** [comment]
Thanks! Will cut a release soon. Please use master in the meantime.

**Pull request merged**
